dist: bionic
language: shell
os: linux
services:
  - docker
addons:
  apt:
    packages:
      - python3-github

env:
  - JOB=cppcheckTest DISTRO="debian:testing"
  - JOB=clangTest DISTRO="debian:testing"

before_install:
  - curl -Ls -o docker-build https://github.com/cafe-desktop/cafe-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./docker-build --name ${DISTRO} --config .$JOB.yml --install


script:
  - ./docker-build --name ${DISTRO} --verbose --config .$JOB.yml --build scripts
