dist: focal
language: shell
os: linux
services:
  - docker
addons:
  apt:
    packages:
      - python3-github

env:
  - JOB=cppcheckTest DISTRO="debian:testing"
  - JOB=clangTest DISTRO="debian:testing"

branches:
  except:
  - gh-pages

before_install:
  - curl -Ls -o docker-build https://github.com/cafe-desktop/cafe-dev-scripts/raw/master/travis/docker-build
  - curl -Ls -o gen-index https://github.com/cafe-desktop/cafe-dev-scripts/raw/master/travis/gen-index.sh
  - chmod +x docker-build gen-index

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./docker-build --name ${DISTRO} --config .$JOB.yml --install


script:
  - ./docker-build --name ${DISTRO} --verbose --config .$JOB.yml --build scripts

deploy:
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    keep_history: false
    committer_from_gh: true
    target_branch: gh-pages
    local_dir: html-report
    strategy: git
    on:
      all_branches: true
      condition: ${DISTRO} =~ ^debian.*$

after_success:
  - 'if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" && "$TRAVIS_PULL_REQUEST" != "false" && ${DISTRO} =~ ^debian.*$ ]]; then
        REPO_SLUG_ARRAY=(${TRAVIS_REPO_SLUG//\// });
        REPO_NAME=${REPO_SLUG_ARRAY[1]};
        COMMENT="Code analysis completed";
        curl -H "Authorization: token $GITHUB_TOKEN" -X POST
           -d "{\"state\": \"success\", \"description\": \"$COMMENT\", \"context\":\"scan-build\", \"target_url\": \"$URL\"}"
           https://api.github.com/repos/${TRAVIS_REPO_SLUG}/statuses/${TRAVIS_PULL_REQUEST_SHA};
     fi'
